
apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: booking-app
  template:
    metadata:
      labels:
        app: booking-app
    spec:
      containers:
        - name: booking-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
