version: "3.8"
services:
  backend:
    build: ./backend
    environment:
      - NODE_ENV=production
    ports:
      - "8080:8080"
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
  proxy:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8000:80"
    depends_on:
      - frontend
